name: Emscripten

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-web:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure resources folder exists
        run: mkdir -p resources

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: build-web/_deps
          key: emscripten-deps-${{ hashFiles('CMakeLists.txt') }}

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: latest
          actions-cache-folder: emsdk-cache

      - name: Verify tools
        run: |
          emcc --version
          cmake --version

      - name: Configure (CMake)
        run: |
          emcmake cmake -B build-web -S . -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: |
          cmake --build build-web --config Release

      - name: Prepare Artifact
        run: |
          mkdir -p dist

          cp build-web/portfolio.* dist/ || true

          cp -r web/* dist/ || true
          cp -r resources dist/resources || true

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy-pages:
    needs: build-web
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4